[mgr]
prepend_keymap = [
  { on = "<C-d>", run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = "<C-u>", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = ["c", "C"], run = 'shell -- $HOME/.config/yazi/copy-files-with-headers.sh $@', desc = "Context to clipboard" }
]
