default_session = "maintenance"
session_sort_order = "LastAttached"
excluded_dirs = [
  "node_modules",
]

[[search_dirs]]
path = "~/Repos/"
depth = 10

[[search_dirs]]
path = "~/zettelkasten/"
depth = 5
